### PR TITLE
fix(ibc-clients/tendermint): disallow empty proof-specs and empty depth range in proof-specs

### LINKED ISSUE #1100: bug(ibc-clients/tendermint): sanity check for `proof_specs` are skipped
## Bug Summary

The `proof_specs` for tendermint client state should validate if they have `min_depth <= max_depth`.

## Details

This is the current `proof_specs` validation.

https://github.com/cosmos/ibc-rs/blob/e048e3400ce5b826b8c6e496fbc54b3a52a2a592/ibc-clients/ics07-tendermint/types/src/client_state.rs#L184-L188

There should be one more check that validates the above inequality. It is best to implement a `validate` method for [`ProofSpecs`](https://github.com/cosmos/ibc-rs/blob/e048e3400ce5b826b8c6e496fbc54b3a52a2a592/ibc-core/ics23-commitment/types/src/specs.rs#L13) that includes all these checks and use it here.

```rs
pub fn validate(&self) -> bool {
  !self.0.is_empty() &&
  self.0.iter().all(|proof_spec| proof_spec.min_depth <= proof_spec.max_depth) 
}
```

## Version

<= 0.50.0

### PR DESCRIPTION
**Pull request by gr4yha7**
Closes: #1100 

______

### PR author checklist:
- [x] Added changelog entry, using [`unclog`](https://github.com/informalsystems/unclog).
- [x] Added tests.
- [x] Linked to GitHub issue.
- [x] Updated code comments and documentation (e.g., `docs/`).
- [x] Tagged *one* reviewer who will be the one responsible for shepherding this PR.

### Reviewer checklist:

- [x] Reviewed `Files changed` in the GitHub PR explorer.
- [x] Manually tested (in case integration/unit/mock tests are absent).

### CODE REVIEW

**Comment by gr4yha7** [comment]
@rnbguy

**Comment by rnbguy** [comment]
Thanks @gr4yha7 ! Can you please add some unit tests to the new `validate()` method?

File: ibc-clients/ics07-tendermint/types/src/client_state.rs [hunk 1]
```diff
@@ -568,7 +594,15 @@ mod tests {
...
                     proof_specs: ProofSpecs::from(Vec::<Ics23ProofSpec>::new()),
-                    ..default_params
+                    ..default_params.clone()
+                },
+                want_pass: false,
+            },
+            Test {
+                name: "Invalid (empty) proof specs depth range".to_string(),
+                params: ClientStateParams {
+                    proof_specs: ProofSpecs::from(empty_depth_range_proof_specs),
```
Comment (rnbguy) [inline ibc-clients/ics07-tendermint/types/src/client_state.rs]: you can directly use

```rs
proof_specs: vec![Ics23ProofSpec {
    leaf_spec: None,
    inner_spec: None,
    min_depth: 2,
    max_depth: 1,
    prehash_key_before_comparison: false,
}].into()
```

as a mock value.

File: ibc-core/ics23-commitment/types/src/error.rs [hunk 2]
```diff
@@ -13,6 +13,10 @@ pub enum CommitmentError {
     EmptyMerkleRoot,
     /// empty verified value
     EmptyVerifiedValue,
+    /// empty proof specs
+    EmptyProofSpecs,
+    /// empty depth range: [{0}, {1}]
+    EmptyDepthRange(i32, i32),
```
Comment (Farhad-Shabani) [inline ibc-core/ics23-commitment/types/src/error.rs]: Just a point caught my eye, we shouldn’t allow negative values too. I opened up another issue (https://github.com/cosmos/ibc-rs/issues/1108) for that. Let’s use `u32` here.

**Review by Farhad-Shabani — CHANGES_REQUESTED** [review]
You may have noticed, just highlighting that there's an implicit check as part of ICS23 [here](https://github.com/cosmos/ics23/blob/9f86b674ada0b03cf0540e2c9484699e6d6bc4f1/rust/src/verify.rs#L121-L133). Though, I'm still in favor of adding an explicit check in ibc-rs to prevent the creation of faulty clients.
 All good, thank you both. Just requested a small fix!

File: ibc-clients/ics07-tendermint/types/src/client_state.rs [hunk 3]
```diff
@@ -176,11 +176,9 @@ impl ClientState {
             });
         }
 
-        // Disallow empty proof-specs
-        if self.proof_specs.is_empty() {
-            return Err(Error::Validation {
-                reason: "ClientState proof-specs cannot be empty".to_string(),
-            });
+        // Sanity checks on client proof specs
+        if let Err(e) = self.proof_specs.validate() {
```
Comment (Farhad-Shabani) [inline ibc-clients/ics07-tendermint/types/src/client_state.rs]: Just another suggestion:
Given the added `InvalidProofSpec`, let's add the following in the `error.rs`

```rust
impl From<CommitmentError> for Error {
    fn from(e: CommitmentError) -> Self {
        Self::InvalidProofSpec(e)
    }
}
```

so that can leave with `self.proof_specs.validate()?`

Comment (rnbguy) [reply ibc-clients/ics07-tendermint/types/src/client_state.rs]: 8a985086

File: ibc-core/ics23-commitment/types/src/error.rs (hunk 2 above)
Comment (rnbguy) [reply ibc-core/ics23-commitment/types/src/error.rs]: Let's use `i32` here, as this is the error report. I check for non-negative values in `.validate()`.

Let's resolve your issue in future PR.

67415960

**Review by Farhad-Shabani — APPROVED** [review]
:pray:

**Comment by rnbguy** [comment]
Thanks @gr4yha7 :pray: nice work :sparkles:

**Comment by gr4yha7** [comment]
> Thanks @gr4yha7 🙏 nice work ✨

Thanks for the assistance @rnbguy
