### PR TITLE
imp(testkit): integration test for packet timeout

### LINKED ISSUE #398: Add needed unit or integration tests for Tendermint proof verifications
## Summary

There is a need to cover Tendermint proof verifications with proper tests after issue #396.
Mock Chain passes the proof verifications and we are not able to catch Tendermint-specific errors with the existing tests. 

## To Do

To ensure Tendermint proof verifications are correctly executed, we should add corresponding unit tests or somehow integrate `basecoin-rs` into our CI process

Blocked on: #677

### LINKED ISSUE #1217: `MsgTimeoutOnClose` verifies wrong proof for closed channel state
## Bug Summary

The current logic for `MsgTimeoutOnClose` uses `proof_unreceived_on_b` instead of `proof_close_on_b` during channel state verification.

## Details

https://github.com/cosmos/ibc-rs/blob/4ea4dcb863efa12f5628a05588e2207112035e4a/ibc-core/ics04-channel/src/handler/timeout_on_close.rs#L105-L118

## Version

till v0.52.0

### PR DESCRIPTION
**Pull request by rnbguy**
Closes: #398
Closes: #1217

## Description

Integration tests for:
- [x] Packet timeout.
- [x] Packet timeout on channel close.

Also, [reproduces the bug](https://github.com/cosmos/ibc-rs/actions/runs/8990023752/job/24694412763?pr=1215#step:5:1301) from #1217.

The latest branch from `basecoin-rs` now has non-membership proofs for its IAVL tree.

This PR adds a packet timeout scenario to our existing integration test. This exercises non-membership proof for the Tendermint light client.

______

### PR author checklist:
- [x] Added changelog entry, using [`unclog`](https://github.com/informalsystems/unclog).
- [x] Added tests.
- [x] Linked to GitHub issue.
- [ ] Updated code comments and documentation (e.g., `docs/`).
- [ ] Tagged *one* reviewer who will be the one responsible for shepherding this PR.

### Reviewer checklist:

- [ ] Reviewed `Files changed` in the GitHub PR explorer.
- [ ] Manually tested (in case integration/unit/mock tests are absent).

### CODE REVIEW

**Comment by rnbguy** [comment]
Let's merge this only after informalsystems/basecoin-rs#141 is merged.

File: ibc-testkit/src/relayer/context.rs [hunk 1]
```diff
@@ -356,4 +356,183 @@ where
             signer,
         )
     }
+
+    /// Timeouts a packet from the first context to the second context.
```
Comment (seanchen1991) [inline ibc-testkit/src/relayer/context.rs]: This language is a bit ambiguous when it comes to delineating whether a packet sent between the two contexts was _**expired**_, or if an actual timeout packet was sent. 

The code seems to indicate the latter, in which case we should say "Sends a timeout packet from the first context to the second context."

Comment (rnbguy) [reply ibc-testkit/src/relayer/context.rs]: I agree with you. I updated the comments and the method names.

3abc78e

**Review by seanchen1991 — APPROVED** [review]
