### PR TITLE
Fix CI

### LINKED ISSUE #149: Tests need the `clock` feature to work
## Summary of Bug
`cargo clippy --no-default-features --all-targets`, which tests `no_std`, currently doesn't work because tests need the `clock` feature (as well as std library), which is included in `std` feature. Therefore the CI fails.

____

## For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate milestone (priority) applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned

### PR DESCRIPTION
**Pull request by plafer**
Closes: #149

______

### PR author checklist:
- [ ] Added changelog entry, using [`unclog`](https://github.com/informalsystems/unclog).
- [ ] Added tests.
- [ ] Linked to GitHub issue.
- [ ] Updated code comments and documentation (e.g., `docs/`).
- [ ] Tagged *one* reviewer who will be the one responsible for shepherding this PR.

### Reviewer checklist:

- [ ] Reviewed `Files changed` in the GitHub PR explorer.
- [ ] Manually tested (in case integration/unit/mock tests are absent).

### CODE REVIEW

File: crates/ibc/src/lib.rs [hunk 1]
```diff
@@ -46,7 +49,7 @@
 
 extern crate alloc;
 
-#[cfg(feature = "std")]
+#[cfg(any(test, feature = "std"))]
```
Comment (hu55a1n1) [inline crates/ibc/src/lib.rs:52]: Is this still required now that we've changed the CI command?

File: .github/workflows/rust.yml [hunk 2]
```diff
@@ -72,7 +72,7 @@ jobs:
       - uses: actions-rs/clippy-check@v1
         with:
           token: ${{ secrets.GITHUB_TOKEN }}
-          args: --no-default-features
+          args: --no-default-features --features "clock" --all-targets # tests need the clock feature
```
Comment (hu55a1n1) [inline .github/workflows/rust.yml:75]: :ok_hand:

File: crates/ibc/src/lib.rs (hunk 1 above)
Comment (plafer) [reply crates/ibc/src/lib.rs:52]: Yes, otherwise we get the "can't find `std`" errors

**Review by hu55a1n1 — APPROVED** [review]
