### PR TITLE
fix TypeInfo implement for Timestamp

### LINKED ISSUE #687: Timestamp ser and der failed on borsh feature
## Bug Summary

Current Timestamp ser and der have failed,
```rust
use borsh::{BorshDeserialize, BorshSerialize};
let timestamp = Timestamp::now();
let encode_timestamp = timestamp.try_to_vec().unwrap();
let _ = Timestamp::try_from_slice(&encode_timestamp).unwrap();
```

report this error:
```bash
Custom { kind: InvalidData, error: "Not all bytes read" }'
```

### PR DESCRIPTION
**Pull request by DaviRain-Su**
Closes: #687 

## Description

When implementing the `parity scale codec` of `Timestamp`, the internal `Time` has been converted to `u64` storage, so here the type `i128` should also be changed to `u64` when implementing `TypeInfo`.

______

### PR author checklist:
- [ ] Added changelog entry, using [`unclog`](https://github.com/informalsystems/unclog).
- [ ] Added tests.
- [ ] Linked to GitHub issue.
- [ ] Updated code comments and documentation (e.g., `docs/`).
- [ ] Tagged *one* reviewer who will be the one responsible for shepherding this PR.

### Reviewer checklist:

- [ ] Reviewed `Files changed` in the GitHub PR explorer.
- [ ] Manually tested (in case integration/unit/mock tests are absent).

### CODE REVIEW

File: crates/ibc/src/core/timestamp.rs [hunk 1]
```diff
@@ -75,12 +75,10 @@ impl scale_info::TypeInfo for Timestamp {
...
             .path(scale_info::Path::new("Timestamp", module_path!()))
-            // i128 is chosen before we represent the timestamp is nanoseconds, which is represented as a i128 by Time
-            .composite(scale_info::build::Fields::named().field(|f| {
-                f.ty::<Option<i128>>()
-                    .name("time")
-                    .type_name("Option<i128>")
-            }))
+            .composite(
+                scale_info::build::Fields::named()
+                    .field(|f| f.ty::<u64>().name("time").type_name("u64")),
```
Comment (Farhad-Shabani) [inline crates/ibc/src/core/timestamp.rs:80]: From what I see, `Timestamp` exceeds 8 bytes, and the `scale_info::Type` with a `time: u64`, will not faithfully represent the `Timestamp`. Wouldn't be an issue with overflow somewhere later?

Comment (DaviRain-Su) [reply crates/ibc/src/core/timestamp.rs:80]: Maybe force conversion to u128？

Comment (Farhad-Shabani) [reply crates/ibc/src/core/timestamp.rs:80]: I believe, what we already have best fits the `Time` and it's ok. 
- The encode/decode has to deal with `u64` because the conversions are performed by `nanoseconds` of `u64` type.
- while the `Time` type within `Timestamp` on its own should have a size of 12 bytes (Considering the inner fields), and the `Option<i128>` represents it correctly.

Hopefully, I am not missing something for your particular use case.  if so, let me know. Happy to learn and be of assistance.

Comment (DaviRain-Su) [reply crates/ibc/src/core/timestamp.rs:80]: I believe using `u64` here is appropriate because I am using the [`nanoseconds()`](https://github.com/cosmos/ibc-rs/blob/d59b303e09b3fbb415d89466dee5e9a119779aa8/crates/ibc/src/core/timestamp.rs#L56) method of the `Timestamp` struct, which is encoded as a `u64` in the `parity-scale-codec crate`. This replaces the original `Option<Time>` field in the `Timestamp` struct with a `u64`. Therefore, I think it is reasonable to declare `Timestamp` as a `u64` here, and when restoring it, I am using the `Timestamp::from_nanoseconds` method to restore it. I believe using `u64` to represent the encoding of `Timestamp` after being encoded by `parity-scale-codec` is appropriate.

Comment (Farhad-Shabani) [reply crates/ibc/src/core/timestamp.rs:80]: > This replaces the original `Option<Time>` field in the Timestamp struct with a u64

:+1:

**Review by Farhad-Shabani — APPROVED** [review]
