### PR TITLE
fix: expire 07-tendermint client when elapsed time from trusted equals trusting period

### LINKED ISSUE #1239: timestamp comparison in client expiration logic
The following inequality should be `>=`

https://github.com/cosmos/ibc-rs/blob/2378cd4ba45094b8ed856ff7dba5f1d0882f59ae/ibc-clients/ics07-tendermint/src/client_state/validation.rs#L224-L225

Considering the [`is_within_trust_period`](https://github.com/informalsystems/tendermint-rs/blob/6399b5b747fc42330b30a51c931a3244002529c4/light-client-verifier/src/predicates.rs#L112-L116) logic from `tendermint-rs`.

To summarize, `tendermint-rs` expires a header at `trusted_header_time + trusting_period`. However, in `ibc-rs`, a header is active till  `trusted_header_time + trusting_period`.

### PR DESCRIPTION
**Pull request by Farhad-Shabani**
Closes: #1239

______

### PR author checklist:
- [X] Added changelog entry, using [`unclog`](https://github.com/informalsystems/unclog).
- [ ] Added tests.
- [X] Linked to GitHub issue.
- [X] Updated code comments and documentation (e.g., `docs/`).
- [X] Tagged *one* reviewer who will be the one responsible for shepherding this PR.

### Reviewer checklist:

- [ ] Reviewed `Files changed` in the GitHub PR explorer.
- [ ] Manually tested (in case integration/unit/mock tests are absent).

### CODE REVIEW

File: tests-integration/tests/core/ics02_client/update_client.rs [hunk 1]
```diff
@@ -1431,7 +1431,7 @@ fn test_expired_client() {
         );
 
     while ctx.ibc_store.host_timestamp().expect("no error")
-        < (timestamp + trusting_period).expect("no error")
+        <= (timestamp + trusting_period).expect("no error")
```
Comment (rnbguy) [inline tests-integration/tests/core/ics02_client/update_client.rs]: Why is this required? I think, the unchanged version is consistent with this PR: _until the latest header is valid, produce blocks_.

Comment (Farhad-Shabani) [reply tests-integration/tests/core/ics02_client/update_client.rs]: Ahh, correct. [a32ad1c](https://github.com/cosmos/ibc-rs/pull/1287/commits/a32ad1cbe2f5cd3ae08418db7a7e26df4071d1a1)

**Review by rnbguy — APPROVED** [review]
