### PR TITLE
Make `ClientState` not optional in `MsgConnectionOpen{Try,Ack}`

### LINKED ISSUE #159: `ClientState` in `MsgConnectionOpenTry` must not be optional
## Summary of Bug

We currently allow the relayer not to send a `ClientState` in `MsgConnectionOpenTry` and `MsgConnectionOpenAck`, and the handler can potentially succeed. This is incorrect. See [ibc-go](https://github.com/cosmos/ibc-go/blob/a1843f8e240bf1c1de5df234b7d65e3cf6777393/modules/core/keeper/msg_server.go#L115-L118) and [the standard](https://github.com/cosmos/ibc/blob/main/spec/core/ics-003-connection-semantics/README.md#opening-handshake) for `OpenTry` (analogous for `OpenAck`).

Related: #15
____

## For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate milestone (priority) applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned

### PR DESCRIPTION
**Pull request by plafer**
Closes: #159
______

### PR author checklist:
- [x] Added changelog entry, using [`unclog`](https://github.com/informalsystems/unclog).
- [x] Added tests.
- [x] Linked to GitHub issue.
- [x] Updated code comments and documentation (e.g., `docs/`).
- [x] Tagged *one* reviewer who will be the one responsible for shepherding this PR.

### Reviewer checklist:

- [ ] Reviewed `Files changed` in the GitHub PR explorer.
- [ ] Manually tested (in case integration/unit/mock tests are absent).

### CODE REVIEW

File: crates/ibc/src/core/ics03_connection/handler/conn_open_confirm.rs [hunk 1]
```diff
@@ -39,15 +39,17 @@ pub(crate) fn process(
...
         ctx,
-        None,
         msg.proofs.height(),
         &conn_end,
         &expected_conn,
-        &msg.proofs,
+        msg.proofs.height(),
+        msg.proofs.object_proof(),
     )?;
+    if let Some(proof) = msg.proofs.consensus_proof() {
```
Comment (hu55a1n1) [inline crates/ibc/src/core/ics03_connection/handler/conn_open_confirm.rs]: I don't think this check is required because `MsgConnectionOpenConfirm` will never have an associated consensus proof.

File: crates/ibc/src/core/ics03_connection/handler/conn_open_confirm.rs [hunk 2]
```diff
@@ -39,15 +39,17 @@ pub(crate) fn process(
         conn_end.delay_period(),
     );
 
-    // 2. Pass the details to the verification function.
-    verify_proofs(
+    verify::verify_connection_proof(
```
Comment (hu55a1n1) [inline crates/ibc/src/core/ics03_connection/handler/conn_open_confirm.rs:42]: Unrelated to this PR, but we're missing `validateSelfClient()`. Will open an issue for this if there already isn't one.

File: crates/ibc/src/core/ics03_connection/handler/verify.rs [hunk 3]
```diff
@@ -28,19 +28,17 @@ pub fn verify_proofs(
...
+        expected_client_state,
+        proofs.height(),
+        proofs
+            .client_proof()
+            .as_ref()
+            .ok_or_else(Error::null_client_proof)?,
+    )?;
 
     // If a consensus proof is attached to the message, then verify it.
     if let Some(proof) = proofs.consensus_proof() {
```
Comment (hu55a1n1) [inline crates/ibc/src/core/ics03_connection/handler/verify.rs:44]: Nit: I think it will be nice to assert here that the `consensus_proof` does exist and is not optional, but we can also do it in a separate PR. Related to #16.

File: crates/ibc/src/core/ics03_connection/msgs/conn_open_ack.rs [hunk 4]
```diff
@@ -20,7 +20,7 @@ pub const TYPE_URL: &str = "/ibc.core.connection.v1.MsgConnectionOpenAck";
 pub struct MsgConnectionOpenAck {
     pub connection_id: ConnectionId,
     pub counterparty_connection_id: ConnectionId,
-    pub client_state: Option<Any>,
+    pub client_state: Any,
```
Comment (hu55a1n1) [inline crates/ibc/src/core/ics03_connection/msgs/conn_open_ack.rs:23]: :ok_hand:

**Review by hu55a1n1 — CHANGES_REQUESTED** [review]

File: crates/ibc/src/core/ics03_connection/handler/conn_open_confirm.rs (hunk 1 above)
Comment (plafer) [reply crates/ibc/src/core/ics03_connection/handler/conn_open_confirm.rs]: Good catch [af02ad3](https://github.com/cosmos/ibc-rs/pull/160/commits/af02ad362d09d8b10234ec414d5a10f11d59d1e0)

File: crates/ibc/src/core/ics03_connection/handler/conn_open_confirm.rs (hunk 2 above)
Comment (plafer) [reply crates/ibc/src/core/ics03_connection/handler/conn_open_confirm.rs:42]: I don't think we have an issue for that yet indeed

Comment (plafer) [reply crates/ibc/src/core/ics03_connection/handler/conn_open_confirm.rs:42]: #162

File: crates/ibc/src/core/ics03_connection/handler/verify.rs (hunk 3 above)
Comment (plafer) [reply crates/ibc/src/core/ics03_connection/handler/verify.rs:44]: Good point; let's address it in #15.

**Review by hu55a1n1 — APPROVED** [review]
