### PR TITLE
Fix upgrade-client issues and refactor relevant tests

### LINKED ISSUE #385: Validate "upgrade_client" implementation by adding unit and integration tests
## Improvement Summary

Validate "upgrade_client" implementation (ADR-06) by adding unit and integration tests

## Proposal

- [ ] Write all the necessary unit tests and correspond them with `IBC-go`
- [ ] Perform integration and hot tests using `basecoin-rs` and `Hermes`
- [ ] Make sure that we are building the right upgrade paths

### LINKED ISSUE #671: [ICS07] try_from `RawClientState` conversion should exclude `ClientState::new` checks
## Problem Statement

It is possible that `MsgUpgradeClient` contains a valid `ClientState`, but it won't necessarily pass checks within [`ClientState::new()`](https://github.com/cosmos/ibc-rs/blob/ee16dc2da38808e3c68c9bdf9fef42f69b3b627d/crates/ibc/src/clients/ics07_tendermint/client_state.rs#L660-L670) when parsed from `Any`. E.g. `trust_level` might be zero, see how [Hermes](https://github.com/informalsystems/hermes/blob/a285c015c604819b213c1582d901e5ef140d3f47/crates/relayer/src/upgrade_chain.rs#L110-L114) creates the `ClientState` for an upgrade proposal.

The ClientState validity checks for the upgrade_client  must be done only after a [`new_client_state`](https://github.com/cosmos/ibc-rs/blob/ee16dc2da38808e3c68c9bdf9fef42f69b3b627d/crates/ibc/src/clients/ics07_tendermint/client_state.rs#L479-L489) is built within the `update_state_with_upgrade_client` process

### LINKED ISSUE #672: [ICS07] Client/ConsensusState bytes for upgrade_client validation should be derived from prost
## Bug Summary

`verify_upgrade_client` method encodes (e.g. [here](https://github.com/cosmos/ibc-rs/blob/ee16dc2da38808e3c68c9bdf9fef42f69b3b627d/crates/ibc/src/clients/ics07_tendermint/client_state.rs#L428-L429)) upgraded_client/cons_state incorrectly.

## Proposal

We should instead use `prost::Message`:
```Rust
        let mut client_state_value = Vec::new();
        upgraded_client_state
            .encode(&mut client_state_value)
            .map_err(ClientError::Encode)?;
```

## Version
v0.40.0

### PR DESCRIPTION
**Pull request by Farhad-Shabani**
Closes: #385
Closes: #671
Closes: #672

## Description
Check out Basecoin-rs [PR99](https://github.com/informalsystems/basecoin-rs/pull/99) for the new integration test covering client upgrades.

**Note:**

- With the current implementation, all comet-based chains can upgrade their clients on hosts using IBC-rs, but hosts for handling an upgrade proposal must figure out the implementation suits their architecture, but can use the newly defined APIs here for setting/getting upgraded_client/cons_state.

- The new APIs haven't been implemented for `MockContext` yet because both it and its storage will be undergoing changes. Additionally, the methods aren't callable anywhere for testing purposes due to the lack of an upgrade proposal handler.

______

### PR author checklist:
- [X] Added changelog entry, using [`unclog`](https://github.com/informalsystems/unclog).
- [x] Added tests.
- [X] Linked to GitHub issue.
- [x] Updated code comments and documentation (e.g., `docs/`).
- [x] Tagged *one* reviewer who will be the one responsible for shepherding this PR.

### Reviewer checklist:

- [ ] Reviewed `Files changed` in the GitHub PR explorer.
- [ ] Manually tested (in case integration/unit/mock tests are absent).

### CODE REVIEW

File: crates/ibc/src/core/ics02_client/handler/upgrade_client.rs [hunk 1]
```diff
@@ -24,13 +21,6 @@ where
 
     ctx.validate_message_signer(&signer)?;
 
-    // Temporary has been disabled until we have a better understanding of some design implications
```
Comment (plafer) [inline crates/ibc/src/core/ics02_client/handler/upgrade_client.rs:27]: I can't find where ibc-go looks if the `old_client_state` is expired; can you point me to it? 

(line 49, GH won't let me put a comment there since it wasn't modified in this PR)

File: crates/ibc/src/core/context.rs [hunk 2]
```diff
@@ -272,13 +285,27 @@ pub trait ExecutionContext: ValidationContext {
         client_state: Box<dyn ClientState>,
     ) -> Result<(), ContextError>;
 
+    /// Sets the upgraded `ClientState` in the upgrade path
+    fn store_upgraded_client_state(
```
Comment (plafer) [inline crates/ibc/src/core/context.rs]: All new upgrade-related methods on `ValidationContext` and `ExecutionContext` are never used. Are they necessary? ibc-go doesn't seem to have any special methods to store an "upgraded" client/consensus state vs a "normal" one

File: crates/ibc/src/core/ics02_client/handler/upgrade_client.rs (hunk 1 above)
Comment (Farhad-Shabani) [reply crates/ibc/src/core/ics02_client/handler/upgrade_client.rs:27]: ofc, [Here](https://github.com/cosmos/ibc-go/blob/c3b12b11f1f60e0c7ba45ccc4c0cd8ae9365e538/modules/core/02-client/keeper/client.go#L125-L127) upon calling the `GetClientStatus` method, it goes through the [status check](https://github.com/cosmos/ibc-go/blob/d840c699d988e32cb55f2c289d69f8ef2e5cea50/modules/core/02-client/keeper/keeper.go#L414)

Comment (plafer) [reply crates/ibc/src/core/ics02_client/handler/upgrade_client.rs:27]: Ah right. The "client expired" check is a [tendermint one though](https://github.com/cosmos/ibc-go/blob/295bab01f633633e0d6136ba9b974c0e248edbe5/modules/light-clients/07-tendermint/client_state.go#L97-L98), so we should have it in the tendermint client instead

File: crates/ibc/src/core/context.rs (hunk 2 above)
Comment (Farhad-Shabani) [reply crates/ibc/src/core/context.rs]: I believe we need them. Ofc, not used yet, but after fixing [this issue](https://github.com/informalsystems/basecoin-rs/issues/100) for basecoin, it will be called for handling upgrade proposals. It's the minimal interface for hosts to interact with the provable stores at the `ClientUpgradePath`, or otherwise they should take care of that in their boundary.
And [here](https://github.com/cosmos/ibc-go/blob/9c6edc4bb828e994645d32108bc4610fe065eb71/modules/core/02-client/types/expected_keepers.go#L17-L26) is the relevant keepers in ibc-go

File: crates/ibc/src/core/ics02_client/handler/upgrade_client.rs (hunk 1 above)
Comment (Farhad-Shabani) [reply crates/ibc/src/core/ics02_client/handler/upgrade_client.rs:27]: I see your point. Just note that, with the current design, having `expired` and even `confirm_not_frozen` as client-wide interfaces, I suggest we mend this while going through #536 and wait for changes from #296
Particularly given that, the `expired` needs a `host_timestamp` from context for calculation, which is not available within the `verify_upgrade_client`

File: crates/ibc/src/core/context.rs (hunk 2 above)
Comment (plafer) [reply crates/ibc/src/core/context.rs]: `ValidationContext` and `ExecutionContext` are the contexts specific to handling all messages in `MsgEnvelope`. This is something else. We'd need some kind of [`HandleUpgradeProposal`](https://github.com/cosmos/ibc-go/blob/295bab01f633633e0d6136ba9b974c0e248edbe5/modules/core/02-client/keeper/proposal.go#L73) contexts (validation & execution), which chains can use to do upgrade proposals. However, I believe you had trouble creating such an abstraction?

File: crates/ibc/src/core/ics02_client/handler/upgrade_client.rs (hunk 1 above)
Comment (plafer) [reply crates/ibc/src/core/ics02_client/handler/upgrade_client.rs:27]: Makes sense

File: crates/ibc/src/core/context.rs (hunk 2 above)
Comment (Farhad-Shabani) [reply crates/ibc/src/core/context.rs]: Hmm, my perspective was a bit different. As we surfaced all the APIs that interact with provable stores within the Validation/Execution contexts, I've placed them there. 
In terms of the abstraction, to have the ability to go over the correctness and functionality of that handler in one go (rather than trial & error), I postponed that for the moment until I add a very simple gov module to the basecoin-rs or maybe even something as basic as possible.
Alright. If so, let me drop them for now, and add them back while finishing #420

Comment (Farhad-Shabani) [reply crates/ibc/src/core/context.rs]: [736a7d2](https://github.com/cosmos/ibc-rs/pull/673/commits/736a7d2e770d46d49e23f3f708fa3340c247c0f7)

**Review by plafer — APPROVED** [review]
👌
