### PR TITLE
fix: add frozen client check for `create_client` handler

### LINKED ISSUE #1061: Ease frozen Height check in tendermint ClientState protobuf deserialization
## Summary

The current implementation, with the frozen height check in [`TryFrom`](https://github.com/cosmos/ibc-rs/blob/main/ibc-clients/ics07-tendermint/types/src/client_state.rs#L244) causes issues for some hosts (see #1040), as it hampers the successful retrieval and deserialization of the `ClientState` during the standard process of converting raw bytes to proto type and then to domain type from the storage.
As within all `ibc-rs` handlers, we check the status of a client by performing the `verify_is_active()` on the retrieved `ClientState`, it’s safe to drop the frozen height check in this proto conversion.  

Props to @riversyang for bringing this up in the first place, and thanks to @rnbguy for spotting it while diving into the `ibc-testkit` refactoring!

## Version
=< 0.50.0

### PR DESCRIPTION
**Pull request by Farhad-Shabani**
Closes: #1061

Fixes #1062 by adding the missing frozen client check in the client creation handler.
______

### PR author checklist:
- [X] Added changelog entry, using [`unclog`](https://github.com/informalsystems/unclog).
- [X] Added tests.
- [X] Linked to GitHub issue.
- [X] Updated code comments and documentation (e.g., `docs/`).
- [X] Tagged *one* reviewer who will be the one responsible for shepherding this PR.

### Reviewer checklist:

- [ ] Reviewed `Files changed` in the GitHub PR explorer.
- [ ] Manually tested (in case integration/unit/mock tests are absent).

### CODE REVIEW

File: ibc-testkit/tests/core/ics02_client/create_client.rs [hunk 1]
```diff
@@ -86,3 +88,36 @@ fn test_tm_create_client_ok() {
...
+    let msg_envelope = MsgEnvelope::from(ClientMsg::from(msg.clone()));
+
+    let res = validate(&ctx, &router, msg_envelope.clone());
+
+    assert!(res.is_err());
+
+    match res.unwrap_err() {
+        ContextError::ClientError(ClientError::ClientFrozen { .. }) => {}
+        e => panic!("unexpected error: {}", e),
+    }
```
Comment (rnbguy) [inline ibc-testkit/tests/core/ics02_client/create_client.rs]: you can combine them as

```rs
    match res {
        Err(ContextError::ClientError(ClientError::ClientFrozen { .. })) => {}
        _ => panic!("unexpected response: {}", res),
    }
```

or a one-liner

 `assert!(matches!(res, Err(ContextError::ClientError(ClientError::ClientFrozen { .. }))))`

**Review by rnbguy — APPROVED** [review]
Looks good ! :raised_hands: Thanks for the test :+1:

File: ibc-testkit/tests/core/ics02_client/create_client.rs (hunk 1 above)
Comment (Farhad-Shabani) [reply ibc-testkit/tests/core/ics02_client/create_client.rs]: [08aef51](https://github.com/cosmos/ibc-rs/pull/1063/commits/08aef510dd922a7cc474baeaf564a20605a6901f)
